### ISSUE TITLE
Interface and design

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/CLIMAParameters.jl#21]
The current package was a stop-gap until we can figure out something more useable. 

In the current package we would have a series of [.toml files](https://github.com/toml-lang/toml); the first would specify the parameter sets:

```toml
# ParameterSets.toml
[ sets.Default ]

[ sets.Earth ]
inherit = "Default"
```

the second would specify the parameters:
```toml
# parameters/Universal.toml

[gas_constant]
description = "Universal gas constant"
units = "J/mol/K"
value.Default = 8.3144598
```

```toml
# parameters/Planet.toml

[molmass_water]
description = "Molecular weight"
units = "kg/mol"
value.Earth = 18.01528e-3
```

```toml
# parameters/Atmos.toml

[SGS.C_smag]
description = "Smagorinsky constant"
units = ""
value.Earth = 0.21
```

We will still keep the idea that parameter sets are types, and parameters are functions, but we have the problem that in Julia you can't subtype concrete types. So what I was thinking is that we could build our own inheritance system, so the above would generate:
```julia
abstract type AbstractParameterSet end

struct Default{FT} <: AbstractParameterSet end
struct Earth{FT} <: AbstractParameterSet end
parent(::Earth{FT}) where {FT} = Default{FT}()
```
and that each parameter would promote if no compatible parameter set was found, e.g.
```julia
gas_constant(ps::AbstractParameterSet) = gas_constant(parent(ps))
gas_constant(::Default{FT}) = FT(8.3144598)
```

Some open questions:
## How to handle derive quantities?

We could allow symbolic expressions, where any non-numeric symbols would be treated as parameters, i.e.
```toml
[molmass_ratio]
derived.Default = "molmass_dryair / molmass_water"
```
would generate:
```julia
molmass_ratio(ps::Default{FT}) = molmass_dryair(ps) / molmass_water(ps)
```

## How to override parameter values

An experiment would provide their own custom Toml file, which would have a simplified version of the above schema:
```toml
# Custom.toml
inherit = "Earth"

[values]
Atmos.SGS.C_smag = 0.20
```

## How to specify a parameter ensemble?
There are two ways we could do this: the first is an [array of tables](https://github.com/toml-lang/toml#array-of-tables):

```toml
# Ensemble1.toml
inherit = "Earth"

[[ ensemble ]]
Atmos.SGS.C_smag = 0.2012

[[ ensemble ]]
Atmos.SGS.C_smag = 0.2194

[[ ensemble ]]
Atmos.SGS.C_smag = 0.2102
```

The second is just specifying arrays for the relevant parameters
```toml
# Ensemble1.toml
inherit = "Earth"

[ ensembles ]
Atmos.SGS.C_smag = [0.2012, 0.2194, 0.2102]
```

## How to specify prior distributions?

TBD...
