### ISSUE TITLE
TOML schema

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/CLIMAParameters.jl#58]
I think there has been a general consensus that we should move to a [TOML](https://toml.io/en/) format. The specifics of how it should be specified in this file need to be clarified.

@odunbar did you have some examples somewhere?

**Comment by simonbyrne** [comment]
What I had been thinking (and is roughly what is implemented in #57) is something like the following:

A **parameter set** file would have the following keys (all are optional unless marked as required)
- `name` (required): the name of the parameter set: this would become the name of the struct in the code, so should be a valid Julia symbolic name
- `inherits_from`: the name of the parameter set to inherit values from
- `parameters`: a [table](https://toml.io/en/v1.0.0#table) of parameters (see below)
- `parameters_include`: an array of relative paths (from the current file) of other .toml files containing parameter tables
- `override_values`: a table of (parameter key, numeric value) pairs describing inherited parameters which should be modified in this parameter set.

A **parameter** is an entry in a table. Each key in the table should be a descriptive but valid Julia symbolic name, e.g. `MolarMassConstant`, and each entry would contain the following keys
- `description`: a long form description of the constant, and necessary references (can be formatted using [Julia Markdown](https://docs.julialang.org/en/v1/stdlib/Markdown/)).
- `symbol`: the standard symbol name used to refer to the parameter
   - should this be required to be unique?
- `units`: a string containing the units of the parameter; should be parsable by [Unitful.jl](https://painterqubits.github.io/Unitful.jl/stable/manipulations/#Unitful.@u_str).
- `value`: the numeric value of the parameter in the current parameter set

Additional keys for UQ (e.g. prior distributions, etc) can also be added. We might also be able to add some mechanism for derived parameters, to support things like 
https://github.com/CliMA/CLIMAParameters.jl/blob/6f660320358bd2be611f382897aacf3084c66bf1/src/Planet/planet_parameters.jl#L5

# Examples

```toml
# default.toml
name = "DefaultParameterSet"

parameters_include = [
 "parameters/universal.toml",
 "parameters/planet.toml",
]
```
```toml
# parameters/universal.toml
[MolarMassConstant]
description = "universal gas constant"
symbol = "R"
units = "J*K^−1*mol^−1"
value = 8.3144598
```
```toml
# custom.toml
name = "CustomParameterSet"
inherits_from = "CLIMAParameters.DefaultParameterSet"

[override_values]
MolarMassConstant = 8.5
```
